language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.1.3
    - extra-android-m2repository
    - android-25

jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-25  ANDROID_ABI=armeabi-v7a MAVEN_OPTS="-XX:MaxPermSize=2048M -Xmx4g -Xms2g"

script: ./gradlew clean build --stacktrace